# Generated by Django 4.0.5 on 2022-07-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegegroups',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college'),
        ),
        migrations.AddField(
            model_name='groupsubjectfaculties',
            name='groupsubjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupsubjects'),
        ),
        migrations.AddField(
            model_name='groupsubjectfaculties',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.faculties'),
        ),
        migrations.AddField(
            model_name='groupsubjectfaculties',
            name='theclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupclasses'),
        ),
        migrations.AddField(
            model_name='groupsubjects',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.collegegroups'),
        ),
        migrations.AddField(
            model_name='groupsubjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.subjects'),
        ),
        migrations.AddField(
            model_name='groupspecifiction',
            name='groupsubjectfaculties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupsubjectfaculties'),
        ),
        migrations.AddField(
            model_name='grouproutine',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.collegegroups'),
        ),
        migrations.AddField(
            model_name='groupclasses',
            name='classfaculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.faculties'),
        ),
        migrations.AddField(
            model_name='groupclasses',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.collegegroups'),
        ),
        migrations.AddField(
            model_name='groupclasses',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.streams'),
        ),
        migrations.AddField(
            model_name='groupbreaks',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.collegegroups'),
        ),
    ]
